# Generated by Django 5.1.7 on 2025-03-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_image_options_alter_parameter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Количество'),
        ),
    ]
