# Generated by Django 5.1.7 on 2025-03-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_parameter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='media/', verbose_name='Файл изображения'),
        ),
    ]
