# Generated by Django 5.1.7 on 2025-03-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='catalog.product', verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
    ]
