# Generated by Django 5.1.7 on 2025-03-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_parameter_product_alter_parameter_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='price',
            new_name='base_price',
        ),
    ]
