# Generated by Django 5.1.7 on 2025-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_parameter_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='file',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Файл изображения'),
        ),
    ]
