# Generated by Django 5.1.7 on 2025-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_parameter_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Файл изображения'),
        ),
    ]
