# Generated by Django 5.1.7 on 2025-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
