# Generated by Django 5.1.7 on 2025-03-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_parameter_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='product_count',
        ),
    ]
