# Generated by Django 5.1.7 on 2025-03-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_parameter_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort_order',
        ),
    ]
